#!/bin/bash

echo "🚀 Render + Netlify Deployment Setup"
echo "===================================="

echo ""
echo "📋 Pre-deployment Checklist:"
echo "-----------------------------"

echo "✅ 1. GitHub repository created and pushed"
echo "   - Repository is public"
echo "   - All code committed and pushed"

echo ""
echo "✅ 2. Stripe keys ready"
echo "   - Test keys for development"
echo "   - Live keys for production"

echo ""
echo "🔗 Step-by-Step Deployment:"
echo "---------------------------"

echo "🌐 1. Deploy Frontend to Netlify:"
echo "   a. Go to: https://netlify.com"
echo "   b. Click 'Add new site' > 'Import from Git'"
echo "   c. Connect your GitHub repository"
echo "   d. Build settings auto-configured ✅"
echo "   e. Add environment variables in Netlify dashboard"

echo ""
echo "🚀 2. Deploy Backend to Render:"
echo "   a. Go to: https://render.com"
echo "   b. Click 'New' > 'Web Service'"
echo "   c. Connect GitHub repository"
echo "   d. Set root directory to: server"
echo "   e. Build command: npm install"
echo "   f. Start command: npm start"
echo "   g. Add environment variables in Render dashboard"

echo ""
echo "🔧 Required Environment Variables:"
echo "----------------------------------"

echo "Netlify (Frontend):"
echo "   VITE_STRIPE_PUBLISHABLE_KEY=pk_test_..."
echo "   VITE_API_URL=https://your-backend.onrender.com"

echo ""
echo "Render (Backend):"
echo "   STRIPE_SECRET_KEY=sk_test_..."
echo "   CLIENT_URL=https://your-site.netlify.app"
echo "   PORT=10000"
echo "   NODE_ENV=production"
echo "   STRIPE_WEBHOOK_SECRET=whsec_..."

echo ""
echo "🧪 Testing Commands:"
echo "-------------------"

echo "1. Test Backend Health:"
echo "   curl https://your-backend.onrender.com/health"

echo ""
echo "2. Test Payment Creation:"
echo "   curl -X POST https://your-backend.onrender.com/create-checkout-session \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"courseName\":\"Test Program\",\"price\":999}'"

echo ""
echo "3. Test Frontend:"
echo "   - Visit: https://your-site.netlify.app"
echo "   - Click any 'Enroll Now' button"
echo "   - Use test card: 4242424242424242"

echo ""
echo "💳 Test Card Numbers:"
echo "---------------------"
echo "✅ Success: 4242424242424242 (any future date, any CVC)"
echo "❌ Declined: 4000000000000002"
echo "💰 Insufficient: 4000000000009995"

echo ""
echo "✅ Success Checklist:"
echo "---------------------"
echo "- [ ] Frontend deploys without errors"
echo "- [ ] Backend API responds to health check"
echo "- [ ] Payment flow works end-to-end"
echo "- [ ] Hash navigation works (#faq, #programs)"
echo "- [ ] Success/cancel redirects work"
echo "- [ ] Mobile responsive"

echo ""
echo "🔗 Useful Links:"
echo "---------------"
echo "• Netlify: https://netlify.com"
echo "• Render: https://render.com"
echo "• Stripe Dashboard: https://dashboard.stripe.com"
echo "• GitHub: https://github.com"

echo ""
echo "💡 Pro Tips:"
echo "-----------"
echo "• Deploy frontend first, then backend"
echo "• Copy Render URL to Netlify environment variables"
echo "• Use test cards first, then live keys"
echo "• Check deployment logs if anything fails"

echo ""
echo "🎉 Ready to Deploy!"
echo "Your meditation app is configured for Render + Netlify!"
echo "Total deployment time: 5-10 minutes"
echo "Monthly cost: $0 (free tiers)"
