#!/bin/bash

echo "🔍 Meditation App - Deployment Verification"
echo "==========================================="

echo ""
echo "📋 Deployment Checklist:"
echo "------------------------"

echo "✅ 1. Frontend deployed successfully"
echo "   - Site loads without errors"
echo "   - All pages render correctly"
echo "   - Hash navigation works (#faq, #programs)"

echo ""
echo "✅ 2. Backend API deployed successfully"
echo "   - Health endpoint responds: GET /health"
echo "   - CORS configured correctly"
echo "   - Environment variables set"

echo ""
echo "✅ 3. Stripe integration working"
echo "   - Live API keys configured"
echo "   - Webhook endpoint set up"
echo "   - Test payments process correctly"

echo ""
echo "🧪 Test Commands:"
echo "-----------------"

echo "1. Test API Health:"
echo "   curl https://your-backend-api.railway.app/health"
echo "   Expected: {\"status\":\"OK\"}"

echo ""
echo "2. Test Payment Creation:"
echo "   curl -X POST https://your-backend-api.railway.app/create-checkout-session \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"courseName\":\"Test Program\",\"price\":999,\"priceId\":\"test\"}'"
echo "   Expected: {\"url\":\"https://checkout.stripe.com/...\"}"

echo ""
echo "3. Test Frontend:"
echo "   - Visit: https://your-site.netlify.app"
echo "   - Click 'Enroll Now' on any program"
echo "   - Complete payment with test card"
echo "   - Verify success/cancel redirects work"

echo ""
echo "🔧 Test Card Numbers (Stripe):"
echo "------------------------------"
echo "✅ Success: 4242424242424242"
echo "❌ Declined: 4000000000000002"
echo "💰 Insufficient: 4000000000009995"
echo "📅 Any future expiry date"
echo "🔐 Any 3-digit CVC"

echo ""
echo "🚨 Common Issues & Solutions:"
echo "-----------------------------"

echo "❌ CORS Error:"
echo "   • Check CLIENT_URL in backend environment"
echo "   • Verify frontend URL matches exactly"

echo ""
echo "❌ Stripe Error:"
echo "   • Verify API keys are live (pk_live_, sk_live_)"
echo "   • Check webhook endpoint URL"
echo "   • Ensure webhook secret matches"

echo ""
echo "❌ Build Error:"
echo "   • Check Node.js version (18.x recommended)"
echo "   • Verify all dependencies installed"
echo "   • Check environment variables"

echo ""
echo "✅ Production Ready Checklist:"
echo "------------------------------"

echo "🔐 Security:"
echo "- [ ] Live Stripe keys (not test keys)"
echo "- [ ] HTTPS only (automatic with deployment platforms)"
echo "- [ ] CORS properly configured"
echo "- [ ] Webhook signature verification"

echo ""
echo "🚀 Performance:"
echo "- [ ] Fast loading times"
echo "- [ ] Mobile responsive"
echo "- [ ] Optimized images"
echo "- [ ] CDN for static assets"

echo ""
echo "💳 Payments:"
echo "- [ ] Real payment processing"
echo "- [ ] Email confirmations"
echo "- [ ] Proper error handling"
echo "- [ ] Success/cancel redirects"

echo ""
echo "📱 User Experience:"
echo "- [ ] All navigation works"
echo "- [ ] Forms submit correctly"
echo "- [ ] Loading states display"
echo "- [ ] Error messages helpful"

echo ""
echo "🎯 Final Steps:"
echo "---------------"
echo "1. Test complete payment flow"
echo "2. Verify email notifications"
echo "3. Set up monitoring (optional)"
echo "4. Configure custom domain (optional)"
echo "5. Go live! 🎉"

echo ""
echo "📞 Need Help?"
echo "-------------"
echo "• Check deployment platform logs"
echo "• Review Stripe dashboard for errors"
echo "• Test with different browsers"
echo "• Validate all environment variables"
