#!/bin/bash

echo "🔍 Render + Netlify Deployment Verification"
echo "==========================================="

echo ""
echo "📋 Deployment Status Check:"
echo "---------------------------"

echo "✅ Step 1: Check GitHub Connection"
echo "   - Repository: https://github.com/aryanverma24/meditation-app"
echo "   - Status: Connected ✅"
echo "   - Latest commit pushed ✅"

echo ""
echo "🌐 Step 2: Frontend (Netlify) Deployment"
echo "   - Site URL: https://your-site-name.netlify.app"
echo "   - Build Status: Check Netlify dashboard"
echo "   - Environment Variables: Set ✅"

echo ""
echo "🚀 Step 3: Backend (Render) Deployment"
echo "   - API URL: https://your-backend-app.onrender.com"
echo "   - Build Status: Check Render dashboard"
echo "   - Environment Variables: Set ✅"

echo ""
echo "🧪 API Testing:"
echo "--------------"

echo "1. Health Check:"
echo "   curl https://your-backend-app.onrender.com/health"
echo "   Expected: {\"status\":\"OK\",\"timestamp\":\"...\"}"

echo ""
echo "2. Payment Creation:"
echo "   curl -X POST https://your-backend-app.onrender.com/create-checkout-session \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"courseName\":\"Test Program\",\"price\":999}'"
echo "   Expected: {\"url\":\"https://checkout.stripe.com/...\"}"

echo ""
echo "💳 Frontend Testing:"
echo "-------------------"

echo "1. Visit: https://your-site-name.netlify.app"
echo "2. Test Features:"
echo "   - [ ] Homepage loads correctly"
echo "   - [ ] Focus test works"
echo "   - [ ] Program enrollment works"
echo "   - [ ] Payment flow completes"
echo "   - [ ] Success/cancel redirects work"
echo "   - [ ] Hash navigation works (#faq, #programs)"

echo ""
echo "🔧 Environment Variables Verification:"
echo "--------------------------------------"

echo "Frontend (.env.local):"
echo "   ✅ VITE_STRIPE_PUBLISHABLE_KEY=pk_test_..."
echo "   ✅ VITE_API_URL=https://your-backend-app.onrender.com"

echo ""
echo "Backend (server/.env):"
echo "   ✅ STRIPE_SECRET_KEY=sk_test_..."
echo "   ✅ CLIENT_URL=https://your-site-name.netlify.app"
echo "   ✅ PORT=10000"
echo "   ✅ NODE_ENV=production"

echo ""
echo "🚨 Common Issues & Solutions:"
echo "-----------------------------"

echo "❌ CORS Error:"
echo "   Solution: Check CLIENT_URL in Render dashboard"
echo "   Make sure it matches your Netlify URL exactly"

echo ""
echo "❌ Build Error:"
echo "   Solution: Check Node.js version (should be 18.x)"
echo "   Verify all dependencies are installed"

echo ""
echo "❌ Payment Error:"
echo "   Solution: Verify Stripe keys are correct"
echo "   Check if webhook endpoint is set up"

echo ""
echo "✅ Production Ready Checklist:"
echo "-------------------------------"

echo "🔐 Security:"
echo "- [ ] Stripe keys are live (not test)"
echo "- [ ] Webhook signature verification"
echo "- [ ] HTTPS only (automatic)"
echo "- [ ] CORS properly configured"

echo ""
echo "🚀 Performance:"
echo "- [ ] Fast loading times"
echo "- [ ] Mobile responsive"
echo "- [ ] All features working"
echo "- [ ] Error handling complete"

echo ""
echo "📱 User Experience:"
echo "- [ ] Navigation works smoothly"
echo "- [ ] Forms submit correctly"
echo "- [ ] Loading states display"
echo "- [ ] Error messages helpful"

echo ""
echo "🎯 Final Steps:"
echo "---------------"
echo "1. Test complete payment flow with real cards"
echo "2. Verify email notifications (if configured)"
echo "3. Set up custom domain (optional)"
echo "4. Monitor performance and errors"
echo "5. Go live! 🎉"

echo ""
echo "📞 Support Resources:"
echo "--------------------"
echo "• Netlify Dashboard: https://app.netlify.com"
echo "• Render Dashboard: https://dashboard.render.com"
echo "• Stripe Dashboard: https://dashboard.stripe.com"
echo "• GitHub Repository: https://github.com/aryanverma24/meditation-app"

echo ""
echo "🎉 Deployment Complete!"
echo "Your meditation website is live and ready for users!"
