# Railway deployment configuration
# This file tells Railway how to deploy your Node.js backend

# Build Command
build = "npm install"

# Start Command
start = "npm start"

# Environment Variables (set these in Railway dashboard)
# STRIPE_SECRET_KEY=sk_live_your_live_key_here
# CLIENT_URL=https://your-netlify-site.netlify.app
# PORT=8080
# STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret_here

# Node.js version
engines = { node = "18.x" }
